name 'rpi-storage'
maintainer 'Don Ebben'
maintainer_email 'don.ebben@gmail.com'
license 'GPL-3'
description 'Adds all detected USB drives on the raspberry pi to fstab'
long_description 'Adds all detected USB drives on the raspberry pi to fstab.'
version '0.0.1'
